# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{backupit}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jinzhu"]
  s.date = %q{2010-10-28}
  s.default_executable = %q{backup}
  s.description = %q{A tool to backup your servers}
  s.email = %q{wosmvp@gmail.com}
  s.executables = ["backup"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "backupit.gemspec",
     "bin/backup",
     "lib/backup.rb",
     "lib/backup/attribute.rb",
     "lib/backup/configuration/base.rb",
     "lib/backup/configuration/mysql.rb",
     "lib/backup/configuration/server.rb",
     "lib/backup/configuration/storage.rb",
     "lib/backup/server.rb",
     "lib/backup/storage.rb",
     "test/helper.rb",
     "test/test_backupit.rb"
  ]
  s.homepage = %q{http://github.com/jinzhu/backupit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tool to backup your servers}
  s.test_files = [
    "test/helper.rb",
     "test/test_backupit.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

