# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{backupit}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jinzhu"]
  s.date = %q{2011-07-11}
  s.default_executable = %q{backup}
  s.description = %q{A tool to backup your servers}
  s.email = %q{wosmvp@gmail.com}
  s.executables = ["backup"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "backupit.gemspec",
    "bin/backup",
    "lib/backup.rb",
    "lib/backup/attribute.rb",
    "lib/backup/configuration/base.rb",
    "lib/backup/configuration/mysql.rb",
    "lib/backup/configuration/server.rb",
    "lib/backup/configuration/storage.rb",
    "lib/backup/server.rb",
    "lib/backup/storage.rb",
    "test/helper.rb",
    "test/test_backupit.rb"
  ]
  s.homepage = %q{http://github.com/jinzhu/backupit}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A tool to backup your servers}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mail>, [">= 0"])
    else
      s.add_dependency(%q<mail>, [">= 0"])
    end
  else
    s.add_dependency(%q<mail>, [">= 0"])
  end
end

